language: node_js

before_script:
  - npm run-script build
  - sudo apt-get install -y lcov

node_js:
  - "10.15"

script:
  - npm test
  - npm run-script integration

after_script:
  - npm run coverage
